### ISSUE TITLE
make folder structure cleaner

### ISSUE THREAD

**Issue by sctech-tr** [anamazingandgreatwebsite/anamazingandgreatwebsite.github.io#8]
please.

i want to help this project but just look at this, PLEASE clean up the structure.

or i can if you want to

**Comment by sctech-tr** [comment]
can i maintain this

**Comment by cobblesteve01** [comment]
I do have to acknowledge that the structure isn't that good. I get it! I just haven't had the time to clean it up. I'll work on it right away, don't worry.
