### ISSUE TITLE
NEW DOMAINS FOR CLASSBOARD COMING SOON

### ISSUE THREAD

**Issue by bahabryra** [anamazingandgreatwebsite/anamazingandgreatwebsite.github.io#9]
I've been working on getting some domains from open-domains

and thanks to the help of @sctech-tr and the @open-domain employyes I think its possible

**Comment by cobblesteve01** [comment]
im pretty sure those domains are blocked for security.domain-sharing

**Comment by bahabryra** [comment]
nope i checked






On Tuesday, December 17, 2024 at 06:43:18 PM CST, andrew ***@***.***> wrote: 







im pretty sure those domains are blocked for security.domain-sharing

**Comment by sctech-tr** [comment]
no, it works and it even has psl support
